### ISSUE TITLE
OauthAllowImplicitFlow set to True. MSAL 2.x apps do not support Implicit flow.

### ISSUE THREAD

**Issue by Tzvetelin88** [Azure-Samples/ms-identity-javascript-v2#17]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hello, I have a question regarding "Oauth2AllowImplicitFlow" option in script "Configure.ps1" 
Why  -Oauth2AllowImplicitFlow is set to True? Is this different Implicit parameter? 

```
$spaAadApplication = New-AzureADApplication -DisplayName "ms-identity-javascript-v2" `
                                               -HomePage "http://localhost:3000/" `
                                               -ReplyUrls "http://localhost:3000/" `
                                               -IdentifierUris "https://$tenantName/ms-identity-javascript-v2" `
                                               -AvailableToOtherTenants $True `
                                               -Oauth2AllowImplicitFlow $true `
                                               -PublicClient $False
```

Reading [more MSAL.js 2.x apps](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-auth-code) do not support Implicit flow. I have tested authentication with and without and it worked in both ways:
![image](https://user-images.githubusercontent.com/9692941/94031687-d4e02500-fdc7-11ea-84ff-bd2cee922d13.png)

[Looking here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows) it seems enabling Implicit will not support refresh token?

**Comment by Tzvetelin88** [comment]
I think this is the answer?
```
Important

MSAL.js 2.0 does not currently support Azure AD B2C for use with the PKCE authorization code flow. At this time, Azure AD B2C recommends using the implicit flow as described in Tutorial: Register an application. To follow progress on this issue, see the MSAL.js wiki.
```

**Comment by derisen** [comment]
@Tzvetelin88 thanks for bringing this up -this needs updating. At the moment, Azure AD Powershell moudle does not allow to creating an application as "Single-page Application" (platform), which breaks the PKCE. So the registration script is not usable right now (with msal 2.x apps -1.x apps are fine).

**Comment by Tzvetelin88** [comment]
Thanks, I see.
So, should I remove checkboxes from Access Tokens and ID tokens from section Implicit grant?
Further more I will check Azure documentation for SAP creation, which I think is here: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow

and I have one last question about redirect URI. If I'm using React, should I specify Redirect URI like http://localhost:3000/auth, where auth is a blank page or I need only http://localhost:3000/ ?

Thanks!

**Comment by derisen** [comment]
You're welcome : ) That right, for the moment please follow the [steps here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow). A [new Azure AD powershell module](https://www.powershellgallery.com/packages/AzureAD/2.0.2.106) has been released yesterday and we are investigating if this is now supported.

Regarding your redirect uri question: both of them should be fine. There's a [react sample here](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo) that you might find useful.

**Comment by derisen** [comment]
Will keep this open until the ps script is updated.
