### ISSUE TITLE
Not working due to bug in msal-browser.js 2.3.1

### ISSUE THREAD

**Issue by fauberon** [Azure-Samples/ms-identity-javascript-v2#21]
## Library

- [X] `@azure/msal-browser@2.3.1`

## Description
See related issue to the msal library here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2476
## Security

- [ ] Is this issue security related?

## Regression

- [X] Did this behavior work before?

Version: 2.3.0

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Configure the app
Run the app
Try to log
Page stays the same as the error occurs in console.
Works with msal-browser 2.3.0

## Expected behavior
After login, the /token request fails as described in the [related issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2476)

The console logs this error: 
msal.js:46 [AcquireTokenSilent] Unhandled Error:TypeError TypeError: Cannot read property 'length' of null
    at Function.ServerTelemetryManager.maxErrorsToSend (index.es.js:7220)
    at ServerTelemetryManager.generateLastRequestHeaderValue (index.es.js:7136)
    at RefreshTokenClient.BaseClient.createDefaultTokenRequestHeaders (index.es.js:4286)
    at RefreshTokenClient.<anonymous> (index.es.js:6357)
    at step (index.es.js:394)
    at Object.next (index.es.js:324)
    at fulfilled (index.es.js:276)

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by derisen** [comment]
@fauberon thanks a lot for catching this. Will do a PR asap to downgrade for the moment until the issue resolves.
