### ISSUE TITLE
showWelcomeMessage wrong argument ??

### ISSUE THREAD

**Issue by PvlD** [Azure-Samples/ms-identity-javascript-v2#27]
username = currentAccounts[0].**username**;
        **showWelcomeMessage**(**username**);

function **showWelcomeMessage**(**account**) {
    // Reconfiguring DOM elements
    cardDiv.style.display = 'initial';
    welcomeDiv.innerHTML = `Welcome ${account.**username**}`;
    signInButton.setAttribute("onclick", "signOut();");
    signInButton.setAttribute('class', "btn btn-success")
    signInButton.innerHTML = "Sign Out";
}

**Comment by derisen** [comment]
@PvlD thanks a lot for catching this. Will fix it asap.
