### ISSUE TITLE
on login -> not getting code back in the response on signIn (getting accessToken back instead)

### ISSUE THREAD

**Issue by mikeyyyzhao** [Azure-Samples/ms-identity-javascript-v2#35]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [x] `@azure/msal-browser@2.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@2.1.3`.
msal@2.1.3

## Security

- [ no ] Is this issue security related?

Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
- download sample app
- `run npm install`
- fill in variables in authConfig.js
- go to `localhost:3000/index.html`
- log in (can log in totally fine)
- gets accessToken back instead of auth code which we need to pass to our backend.

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
Get auth code back in the response but currently only getting authToken back instead.

## Browsers/Environment

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by derisen** [comment]
Closing as [duplicate](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4931).
