### ISSUE TITLE
TS2322: Type 'string | undefined' is not assignable to type 'string'

### ISSUE THREAD

**Issue by DarkLite1** [Azure-Samples/ms-identity-javascript-v2#4]
In our project we upgraded from `msal 1.3.0` to `"@azure/msal-browser": "^2.0.0-beta.2"`. Everything seems to work fine except for the following TypeScript error message:

> TS2322: Type 'string | undefined' is not assignable to type 'string'.

This comes from expecting the `idTokenClaims.oid` to be a string:

```js
const accountID = ref('')

export const setAccountID = () => {
  const account = auth.getAccount()

  if (account) {
    accountID.value = account.idTokenClaims.oid
  } else {
    accountID.value = ''
  }
}
```

In the old library this was not an issue. Should the property `oid` not [always be populated](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1620) with a string when `getAccount()` is successful as it identifies the logged on user?

Our current workaround is this:
```js
const accountID = ref('')

export const setAccountID = () => {
  const account = auth.getAccount()

  if (account) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    accountID.value = account.idTokenClaims.oid!
  } else {
    accountID.value = ''
  }
}
```

Being fairly new to TypeScript and web development in general I was wondering if I did something wrong or if there's a better way to handle this? Full code can be found [here](https://github.com/DarkLite1/hip/blob/test-msal-2/src/comp-functions/useAccount.ts).

**Comment by derisen** [comment]
This looks more to do with TypeScript than with MSAL. And I would say there's nothing wrong here. In case `auth.getAccount()` fails for some reason, your `account` variable will be set to `null`, so `oid` will be `null` too. So you are asserting that it will not be null with the (!) mark. (but yeah `oid` will be always be a string as long as `getAccount()` succeeds)

You could of course ask why should `getAccount()` return null when fails and not something else on [msal.js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues).

**Comment by DarkLite1** [comment]
I've looked a bit further into this. When you look at [Account.ts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/Account.ts) you see the following lines:

```js
import { StringDict } from "./MsalTypes";
idTokenClaims: StringDict;
```
When verifying [MsalTypes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/MsalTypes.ts) we see this:

```js
export type StringDict = {[key: string]: string};
```

The issue with this setup is that the property `oid` on the object `idTokenClaims` can be `undefined` when it's not added. I think this is why TS fails to see that there is always an `oid` property when `getAccount()` succeeds.

If I got this wrong please correct me. As I see it now there are 3 options:
- Either TS should be smart enough to see that the property `oid` is always there when `getAccount()` succeeds, this is not the case, so there should be a bug report at TS for this issue.
- TS is correct but the type definition in the msal library is incorrect and should be corrected. So that the property `oid` is hard coded on the `idTokenClaims` property.
- I got it totally wrong, which happens :D

**Comment by derisen** [comment]
Hmm, I would think that the option 2 is more likely. Could you raise this issue in [msal.js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues)? Not quite sure what was the expectation from server with `idTokenClaims`.

**Comment by DarkLite1** [comment]
Closing this one for the new issue created.
