### ISSUE TITLE
The reference document link in README.md is Implicit grant flow.

### ISSUE THREAD

**Issue by g-child** [Azure-Samples/ms-identity-javascript-v2#7]
In Readme.md line 55, The link to "For more information, see the documentation" in 1.3 of "Running the sample" is below, 
but this is the Quickstart of Implict grant Flow.

https://docs.microsoft.com/azure/active-directory/develop/quickstart-v2-javascript

The following authentication code flow Quickstart also exists, so it is better to change.

https://docs.microsoft.com/azure/active-directory/develop/quickstart-v2-javascript-auth-code

Can I create Pull Requests to fix link?

**Comment by derisen** [comment]
@g-child good catch! Please go ahead and make a PR if you like.

**Comment by g-child** [comment]
@derisen 
Can you review PR?
I tried to set the reviewer to PR, but it doesn't seem to work with my account.
